// web/src/pages/events/page.tsx
import { useMemo, useRef, useState } from "react";
import { Pause, Play } from "lucide-react";
import { useAppState } from "@/hooks/use-app-state";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { cn, formatRelativeTime } from "@/lib/utils";
import type { Event } from "@/lib/types";

// ---------------------------------------------------------------------------
// Filter categories
// ---------------------------------------------------------------------------

const FILTERS = [
  { key: "all", label: "All" },
  { key: "task", label: "Task" },
  { key: "agent", label: "Agent" },
  { key: "merge", label: "Merge" },
  { key: "system", label: "System" },
  { key: "orchestrator", label: "Orchestrator" },
] as const;

type FilterKey = (typeof FILTERS)[number]["key"];

// ---------------------------------------------------------------------------
// Event type badge colors
// ---------------------------------------------------------------------------

function badgeClasses(type: string): string {
  if (type.startsWith("task:")) return "bg-blue-500/15 text-blue-600 border-blue-500/30";
  if (type.startsWith("agent:")) return "bg-green-500/15 text-green-600 border-green-500/30";
  if (type.startsWith("merge:")) return "bg-purple-500/15 text-purple-600 border-purple-500/30";
  if (type.startsWith("system:")) return "bg-gray-500/15 text-gray-600 border-gray-500/30";
  if (type.startsWith("orchestrator:")) return "bg-orange-500/15 text-orange-600 border-orange-500/30";
  return "bg-muted text-muted-foreground";
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function matchesFilter(event: Event, filter: FilterKey): boolean {
  if (filter === "all") return true;
  return event.type.startsWith(`${filter}:`);
}

function truncateData(data: Record<string, unknown>, max = 100): string {
  const raw = JSON.stringify(data);
  return raw.length > max ? `${raw.slice(0, max)}...` : raw;
}

// ---------------------------------------------------------------------------
// Events page
// ---------------------------------------------------------------------------

export function EventsPage() {
  const { events: liveEvents } = useAppState();
  const [activeFilter, setActiveFilter] = useState<FilterKey>("all");
  const [paused, setPaused] = useState(false);

  // When the user pauses, freeze the current event list into the ref.
  const frozenRef = useRef<Event[]>([]);

  function handleTogglePause() {
    if (!paused) {
      // Freezing: capture current live events.
      frozenRef.current = liveEvents;
    }
    setPaused((prev) => !prev);
  }

  const events = paused ? frozenRef.current : liveEvents;

  const filteredEvents = useMemo(
    () => events.filter((e) => matchesFilter(e, activeFilter)),
    [events, activeFilter],
  );

  return (
    <div className="flex flex-col h-full">
      {/* Toolbar */}
      <div className="flex items-center justify-between gap-4 border-b border-border px-6 py-3">
        {/* Filter buttons */}
        <div className="flex items-center gap-1.5 flex-wrap">
          {FILTERS.map(({ key, label }) => (
            <Button
              key={key}
              size="sm"
              variant={activeFilter === key ? "default" : "outline"}
              onClick={() => setActiveFilter(key)}
              className="h-7 text-xs"
            >
              {label}
            </Button>
          ))}
        </div>

        {/* Pause / Resume */}
        <Button
          size="sm"
          variant="outline"
          onClick={handleTogglePause}
          className="gap-1.5 shrink-0"
        >
          {paused ? (
            <>
              <Play className="h-3.5 w-3.5" />
              Resume
            </>
          ) : (
            <>
              <Pause className="h-3.5 w-3.5" />
              Pause
            </>
          )}
        </Button>
      </div>

      {/* Events table */}
      <div className="flex-1 overflow-auto">
        {filteredEvents.length === 0 ? (
          <div className="flex items-center justify-center h-full py-32">
            <p className="text-muted-foreground text-sm">
              {paused ? "No events match the current filter (paused)." : "No events yet."}
            </p>
          </div>
        ) : (
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-[100px]">Time</TableHead>
                <TableHead className="w-[180px]">Type</TableHead>
                <TableHead className="w-[110px]">Actor</TableHead>
                <TableHead className="w-[90px]">Task</TableHead>
                <TableHead>Data</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filteredEvents.map((event) => (
                <TableRow key={event.id}>
                  <TableCell className="text-xs text-muted-foreground whitespace-nowrap">
                    {formatRelativeTime(event.ts)}
                  </TableCell>
                  <TableCell>
                    <Badge
                      variant="outline"
                      className={cn("text-xs font-mono", badgeClasses(event.type))}
                    >
                      {event.type}
                    </Badge>
                  </TableCell>
                  <TableCell className="text-sm">{event.actor}</TableCell>
                  <TableCell className="font-mono text-xs text-muted-foreground">
                    {event.task ? event.task.slice(0, 8) : "\u2014"}
                  </TableCell>
                  <TableCell className="text-xs text-muted-foreground max-w-[400px] truncate font-mono">
                    {truncateData(event.data)}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        )}
      </div>
    </div>
  );
}

export default EventsPage;

// web/src/routes/events/+page.svelte
<script lang="ts">
	import { getAppState } from '$lib/stores/app.svelte';
	import type { Event } from '$lib/types';

	const app = getAppState();

	let filterType = $state('all');
	let paused = $state(false);

	const typeGroups = [
		{ label: 'All', value: 'all' },
		{ label: 'Task', value: 'task:' },
		{ label: 'Agent', value: 'agent:' },
		{ label: 'Merge', value: 'merge:' },
		{ label: 'System', value: 'system:' },
		{ label: 'Orchestrator', value: 'orchestrator:' }
	];

	function filteredEvents(): Event[] {
		if (filterType === 'all') return app.events;
		return app.events.filter((e) => e.type.startsWith(filterType));
	}

	function formatTime(ts: string): string {
		return new Date(ts).toLocaleTimeString();
	}

	function timeAgo(ts: string): string {
		const diff = Date.now() - new Date(ts).getTime();
		const secs = Math.floor(diff / 1000);
		if (secs < 5) return 'now';
		if (secs < 60) return `${secs}s ago`;
		const mins = Math.floor(secs / 60);
		if (mins < 60) return `${mins}m ago`;
		return `${Math.floor(mins / 60)}h ago`;
	}

	const eventTypeColors: Record<string, string> = {
		'task:created': 'badge-info',
		'task:state:running': 'badge-success',
		'task:state:question': 'badge-warning',
		'task:state:completed': 'badge-success badge-outline',
		'task:state:failed': 'badge-error',
		'task:state:cancelled': 'badge-ghost',
		'agent:message': 'badge-info badge-outline',
		'agent:question': 'badge-warning',
		'agent:error': 'badge-error',
		'merge:queued': 'badge-primary badge-outline',
		'merge:approved': 'badge-success',
		'merge:completed': 'badge-primary',
		'merge:conflict': 'badge-error',
		'system:started': 'badge-info',
		'system:mode:play': 'badge-success',
		'system:mode:pause': 'badge-warning',
		'system:mode:stop': 'badge-error'
	};
</script>

<div class="p-6 max-w-5xl mx-auto space-y-4">
	<div class="flex items-center justify-between">
		<h2 class="text-2xl font-bold">Events</h2>
		<div class="flex items-center gap-2">
			<span class="text-sm opacity-50">{filteredEvents().length} events</span>
			<button
				class="btn btn-sm btn-ghost"
				class:btn-active={paused}
				onclick={() => (paused = !paused)}
			>
				{paused ? 'Resume' : 'Pause'}
			</button>
		</div>
	</div>

	<!-- Type filter -->
	<div class="flex flex-wrap gap-2">
		{#each typeGroups as group}
			<button
				class="btn btn-xs"
				class:btn-active={filterType === group.value}
				onclick={() => (filterType = group.value)}
			>
				{group.label}
			</button>
		{/each}
	</div>

	<!-- Event stream -->
	<div class="bg-base-200 rounded-xl overflow-hidden">
		<div class="max-h-[calc(100vh-200px)] overflow-auto">
			<table class="table table-xs w-full">
				<thead class="sticky top-0 bg-base-200">
					<tr>
						<th class="w-20">Time</th>
						<th class="w-44">Type</th>
						<th class="w-20">Actor</th>
						<th class="w-24">Task</th>
						<th>Data</th>
					</tr>
				</thead>
				<tbody class="font-mono text-xs">
					{#each filteredEvents() as event}
						<tr class="hover:bg-base-300">
							<td class="opacity-40">{formatTime(event.ts)}</td>
							<td>
								<span class="badge badge-xs {eventTypeColors[event.type] ?? 'badge-ghost'}">
									{event.type}
								</span>
							</td>
							<td class="opacity-60">{event.actor}</td>
							<td>
								{#if event.task !== 'system'}
									<a href="/tasks/{event.task}" class="link link-hover">
										{event.task.slice(0, 8)}
									</a>
								{:else}
									<span class="opacity-40">system</span>
								{/if}
							</td>
							<td class="opacity-40 truncate max-w-xs">
								{Object.keys(event.data).length > 0 ? JSON.stringify(event.data) : ''}
							</td>
						</tr>
					{/each}
				</tbody>
			</table>

			{#if filteredEvents().length === 0}
				<div class="p-8 text-center text-sm opacity-50">
					No events to display. Events will appear here as they occur.
				</div>
			{/if}
		</div>
	</div>
</div>
