// web/src/pages/tasks/page.tsx
import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import {
  ArrowDown,
  ArrowRight,
  ArrowUp,
  ChevronRight,
  Minus,
  Search,
} from "lucide-react";
import { useAppState } from "@/hooks/use-app-state";
import { cn, formatRelativeTime } from "@/lib/utils";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ScrollArea } from "@/components/ui/scroll-area";
import type { Task, TaskState } from "@/lib/types";
import { taskStateMeta, stateSortOrder } from "./columns";

// ---------------------------------------------------------------------------
// Tab definitions
// ---------------------------------------------------------------------------

type TabKey = "all" | "active" | "completed";

const ACTIVE_STATES: TaskState[] = [
  "running",
  "question",
  "testing",
  "awaiting_merge",
  "conflict",
  "waiting",
  "blocked",
];

const COMPLETED_STATES: TaskState[] = ["completed", "failed", "cancelled"];

function filterByTab(tasks: Task[], tab: TabKey): Task[] {
  switch (tab) {
    case "active":
      return tasks.filter((t) => ACTIVE_STATES.includes(t.state));
    case "completed":
      return tasks.filter((t) => COMPLETED_STATES.includes(t.state));
    default:
      return tasks;
  }
}

// ---------------------------------------------------------------------------
// Group tasks by state
// ---------------------------------------------------------------------------

interface TaskGroup {
  state: TaskState;
  tasks: Task[];
}

function groupByState(tasks: Task[]): TaskGroup[] {
  const groups = new Map<TaskState, Task[]>();
  for (const task of tasks) {
    const existing = groups.get(task.state);
    if (existing) {
      existing.push(task);
    } else {
      groups.set(task.state, [task]);
    }
  }

  return Array.from(groups.entries())
    .sort(([a], [b]) => (stateSortOrder[a] ?? 999) - (stateSortOrder[b] ?? 999))
    .map(([state, tasks]) => ({
      state,
      tasks: tasks.sort(
        (a, b) => new Date(b.updated_at).getTime() - new Date(a.updated_at).getTime()
      ),
    }));
}

// ---------------------------------------------------------------------------
// Priority indicator
// ---------------------------------------------------------------------------

const priorityConfig: Record<
  number,
  { icon: typeof ArrowUp; className: string }
> = {
  1: { icon: ArrowUp, className: "text-red-500" },
  2: { icon: ArrowRight, className: "text-yellow-500" },
  3: { icon: ArrowDown, className: "text-blue-500" },
};

function PriorityIcon({ priority }: { priority: number | null }) {
  if (priority == null) {
    return <Minus className="h-3.5 w-3.5 text-muted-foreground/50" />;
  }
  const config = priorityConfig[priority];
  if (!config) {
    return <Minus className="h-3.5 w-3.5 text-muted-foreground/50" />;
  }
  const Icon = config.icon;
  return <Icon className={cn("h-3.5 w-3.5", config.className)} />;
}

// ---------------------------------------------------------------------------
// Task row
// ---------------------------------------------------------------------------

function TaskRow({
  task,
  projectName,
}: {
  task: Task;
  projectName: string;
}) {
  const navigate = useNavigate();
  const meta = taskStateMeta[task.state];
  const StateIcon = meta?.icon;

  const idLabel =
    task.source.type === "github_issue" || task.source.type === "github_pr"
      ? `#${task.source.number}`
      : task.id.slice(0, 8);

  return (
    <button
      onClick={() => navigate(`/tasks/${task.id}`)}
      className="flex w-full items-center gap-3 px-4 py-2 text-left hover:bg-accent/50 transition-colors border-b border-border last:border-b-0"
    >
      {/* Priority */}
      <PriorityIcon priority={task.priority} />

      {/* ID */}
      <span className="w-16 shrink-0 font-mono text-xs text-muted-foreground">
        {idLabel}
      </span>

      {/* State icon */}
      {StateIcon && (
        <StateIcon className={cn("h-4 w-4 shrink-0", meta.color)} />
      )}

      {/* Title */}
      <span className="flex-1 truncate text-sm">{task.title}</span>

      {/* Labels */}
      {task.labels.map((label) => (
        <Badge key={label} variant="outline" className="text-xs shrink-0">
          {label}
        </Badge>
      ))}

      {/* Project */}
      <span className="shrink-0 text-xs text-muted-foreground">
        {projectName}
      </span>

      {/* Updated */}
      <span className="w-16 shrink-0 text-right text-xs text-muted-foreground">
        {formatRelativeTime(task.updated_at)}
      </span>
    </button>
  );
}

// ---------------------------------------------------------------------------
// Collapsible group
// ---------------------------------------------------------------------------

function TaskGroupSection({
  group,
  projectIdToRepo,
  defaultOpen,
}: {
  group: TaskGroup;
  projectIdToRepo: Record<string, string>;
  defaultOpen: boolean;
}) {
  const [isOpen, setIsOpen] = useState(defaultOpen);
  const meta = taskStateMeta[group.state];
  const StateIcon = meta?.icon;

  return (
    <div>
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex w-full items-center gap-2 px-4 py-2 text-sm hover:bg-accent/30 transition-colors"
      >
        <ChevronRight
          className={cn(
            "h-3.5 w-3.5 text-muted-foreground transition-transform",
            isOpen && "rotate-90"
          )}
        />
        {StateIcon && (
          <StateIcon className={cn("h-4 w-4", meta.color)} />
        )}
        <span className="font-medium">{meta?.label ?? group.state}</span>
        <span className="text-xs text-muted-foreground">{group.tasks.length}</span>
      </button>
      {isOpen && (
        <div>
          {group.tasks.map((task) => (
            <TaskRow
              key={task.id}
              task={task}
              projectName={projectIdToRepo[task.project] ?? task.project}
            />
          ))}
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Tasks Page
// ---------------------------------------------------------------------------

export function TasksPage() {
  const { filteredTasks, selectedProject, snapshot } = useAppState();
  const [activeTab, setActiveTab] = useState<TabKey>("all");
  const [search, setSearch] = useState("");

  const projects = snapshot?.projects ?? [];
  const projectIdToRepo = useMemo(() => {
    const map: Record<string, string> = {};
    for (const p of projects) {
      map[p.id] = p.repo;
    }
    return map;
  }, [projects]);

  // Filter by tab and search
  const displayedTasks = useMemo(() => {
    let tasks = filterByTab(filteredTasks, activeTab);
    if (search.trim()) {
      const q = search.toLowerCase();
      tasks = tasks.filter(
        (t) =>
          t.title.toLowerCase().includes(q) ||
          t.id.toLowerCase().includes(q)
      );
    }
    return tasks;
  }, [filteredTasks, activeTab, search]);

  const groups = useMemo(() => groupByState(displayedTasks), [displayedTasks]);

  // Tab counts
  const counts = useMemo(() => {
    const all = filteredTasks.length;
    const active = filteredTasks.filter((t) => ACTIVE_STATES.includes(t.state)).length;
    const completed = filteredTasks.filter((t) => COMPLETED_STATES.includes(t.state)).length;
    return { all, active, completed };
  }, [filteredTasks]);

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-border px-4 py-2.5">
        <div className="flex items-center gap-4">
          <h1 className="text-sm font-semibold">
            {selectedProject
              ? projectIdToRepo[selectedProject] ?? "Project"
              : "Tasks"}
          </h1>

          <Tabs
            value={activeTab}
            onValueChange={(v: string) => setActiveTab(v as TabKey)}
          >
            <TabsList className="h-7">
              <TabsTrigger value="all" className="text-xs px-2.5 h-6">
                All {counts.all > 0 && <span className="ml-1 text-muted-foreground">{counts.all}</span>}
              </TabsTrigger>
              <TabsTrigger value="active" className="text-xs px-2.5 h-6">
                Active {counts.active > 0 && <span className="ml-1 text-muted-foreground">{counts.active}</span>}
              </TabsTrigger>
              <TabsTrigger value="completed" className="text-xs px-2.5 h-6">
                Done {counts.completed > 0 && <span className="ml-1 text-muted-foreground">{counts.completed}</span>}
              </TabsTrigger>
            </TabsList>
          </Tabs>
        </div>

        <div className="relative w-48">
          <Search className="absolute left-2 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-muted-foreground" />
          <Input
            placeholder="Filter..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="h-7 pl-7 text-xs"
          />
        </div>
      </div>

      {/* Task list */}
      <ScrollArea className="flex-1">
        {groups.length === 0 ? (
          <div className="flex items-center justify-center py-20">
            <p className="text-sm text-muted-foreground">
              {search ? "No tasks match your search." : "No tasks."}
            </p>
          </div>
        ) : (
          <div>
            {groups.map((group) => (
              <TaskGroupSection
                key={group.state}
                group={group}
                projectIdToRepo={projectIdToRepo}
                defaultOpen={!COMPLETED_STATES.includes(group.state)}
              />
            ))}
          </div>
        )}
      </ScrollArea>
    </div>
  );
}

// web/src/routes/tasks/+page.svelte
<script lang="ts">
	import { getAppState } from '$lib/stores/app.svelte';
	import TaskStateBadge from '$lib/components/TaskStateBadge.svelte';
	import type { Task, TaskState } from '$lib/types';

	const app = getAppState();

	let filterState = $state<TaskState | 'all'>('all');
	let filterProject = $state<string>('all');
	let search = $state('');

	function filteredTasks(): Task[] {
		let tasks = app.tasks;
		if (filterState !== 'all') {
			tasks = tasks.filter((t) => t.state === filterState);
		}
		if (filterProject !== 'all') {
			tasks = tasks.filter((t) => t.project === filterProject);
		}
		if (search) {
			const q = search.toLowerCase();
			tasks = tasks.filter(
				(t) =>
					t.title.toLowerCase().includes(q) ||
					t.id.toLowerCase().includes(q)
			);
		}
		return tasks.sort(
			(a, b) => new Date(b.updated_at).getTime() - new Date(a.updated_at).getTime()
		);
	}

	function sourceLabel(task: Task): string {
		if (task.source.type === 'github_issue') return `#${task.source.number}`;
		if (task.source.type === 'github_pr') return `PR #${task.source.number}`;
		return 'internal';
	}

	function sourceUrl(task: Task): string | null {
		if (task.source.type === 'github_issue') {
			return `https://github.com/${task.source.owner}/${task.source.repo}/issues/${task.source.number}`;
		}
		if (task.source.type === 'github_pr') {
			return `https://github.com/${task.source.owner}/${task.source.repo}/pull/${task.source.number}`;
		}
		return null;
	}

	function timeAgo(ts: string): string {
		const diff = Date.now() - new Date(ts).getTime();
		const mins = Math.floor(diff / 60000);
		if (mins < 1) return 'just now';
		if (mins < 60) return `${mins}m ago`;
		const hours = Math.floor(mins / 60);
		if (hours < 24) return `${hours}h ago`;
		return `${Math.floor(hours / 24)}d ago`;
	}

	const states: (TaskState | 'all')[] = [
		'all',
		'running',
		'question',
		'testing',
		'waiting',
		'blocked',
		'awaiting_merge',
		'conflict',
		'completed',
		'failed',
		'cancelled'
	];
</script>

<div class="p-6 max-w-6xl mx-auto space-y-4">
	<div class="flex items-center justify-between">
		<h2 class="text-2xl font-bold">Tasks</h2>
		<span class="text-sm opacity-50">{filteredTasks().length} tasks</span>
	</div>

	<!-- Filters -->
	<div class="flex flex-wrap gap-3">
		<input
			type="text"
			placeholder="Search tasks..."
			class="input input-sm input-bordered w-64"
			bind:value={search}
		/>

		<select class="select select-sm select-bordered" bind:value={filterState}>
			{#each states as s}
				<option value={s}>{s === 'all' ? 'All states' : s.replace('_', ' ')}</option>
			{/each}
		</select>

		{#if app.projects.length > 1}
			<select class="select select-sm select-bordered" bind:value={filterProject}>
				<option value="all">All projects</option>
				{#each app.projects as p}
					<option value={p.id}>{p.repo}</option>
				{/each}
			</select>
		{/if}
	</div>

	<!-- Task list -->
	<div class="bg-base-200 rounded-xl overflow-hidden">
		<table class="table table-sm w-full">
			<thead>
				<tr class="text-xs">
					<th>State</th>
					<th>Task</th>
					<th>Source</th>
					<th>Project</th>
					<th>Priority</th>
					<th>Updated</th>
				</tr>
			</thead>
			<tbody>
				{#each filteredTasks() as task}
					<tr class="hover:bg-base-300 transition-colors">
						<td>
							<TaskStateBadge state={task.state} />
						</td>
						<td>
							<a href="/tasks/{task.id}" class="link link-hover font-medium">
								{task.title}
							</a>
							{#if task.labels.length > 0}
								<div class="flex gap-1 mt-0.5">
									{#each task.labels.slice(0, 3) as label}
										<span class="badge badge-ghost badge-xs">{label}</span>
									{/each}
								</div>
							{/if}
						</td>
						<td class="text-xs">
							{#if sourceUrl(task)}
								<a href={sourceUrl(task)} target="_blank" rel="noopener" class="link link-hover">
									{sourceLabel(task)}
								</a>
							{:else}
								{sourceLabel(task)}
							{/if}
						</td>
						<td class="text-xs opacity-60">{task.project}</td>
						<td class="text-xs font-mono">
							{task.priority !== null ? task.priority : '-'}
						</td>
						<td class="text-xs opacity-50">{timeAgo(task.updated_at)}</td>
					</tr>
				{/each}
			</tbody>
		</table>

		{#if filteredTasks().length === 0}
			<div class="p-8 text-center text-sm opacity-50">
				No tasks match your filters
			</div>
		{/if}
	</div>
</div>
